### ISSUE TITLE
Auth fails

### ISSUE THREAD

**Issue by rossjones** [scraperwiki/twitter-search-tool#11]
I created a new twitter scraper with a silly search term 'a' and got the follow stacktrace:

``` python
Traceback (most recent call last):
  File "tool/get.py", line 208, in 
    results = tw.search.tweets(q=query_terms, since_id = max_id)
  File "/usr/local/lib/python2.7/dist-packages/twitter/api.py", line 204, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "/usr/local/lib/python2.7/dist-packages/twitter/api.py", line 235, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 403 for URL: 1.1/search/tweets.json using parameters: (oauth_consumer_key=CONSUMER_KEY&oauth_nonce=OAUTH_NONCE&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1373456202&oauth_token=OAUTH_TOKEN&oauth_version=1.0&q=%2A&since_id=None&oauth_signature=OAUTH_SIGNATURE%3D)
details: {"errors":[{"code":195,"message":"Missing or invalid url parameter"}]}
```

**Comment by frabcus** [comment]
Aha! Looking at the error, I think you mean the search term of one asterisk \* rather than 'a'?

**Comment by frabcus** [comment]
Yeah, so queries like just a \* or an = are invalid. The Twitter API throws that TwitterHTTPError with undocumented code 195. I guess I'll use that.

**Comment by frabcus** [comment]
Fixed, it now shows a better error for that case.
